fastlane_require 'octokit'

lane :update do
  all_sponsors = fetch_sponsors(page_size: 100).sort_by(&:createdAt)

  public_sponsors = all_sponsors.select do |sponsor|
    sponsor[:privacyLevel] == "PUBLIC"
  end
  private_sponsors = all_sponsors.select do |sponsor|
    sponsor[:privacyLevel] != "PUBLIC"
  end

  erb(
    template: "fastlane/README.md.erb",
    destination: "README.md",
    placeholders: {
      :sponsors_top_8 => public_sponsors[0...8] || [],
      :sponsors_the_rest => public_sponsors[8..-1] || [],
      :private_sponsor_count => private_sponsors.size
    },
    trim_mode: "-"
  )

  git_add(path: "./README.md")
  git_commit(path: "./README.md", message: "Updated with fastlane")
  push_to_git_remote
end

private_lane :fetch_sponsors do |options|
  sponsors = []

  client = Octokit::Client.new(access_token: ENV['GH_TOKEN'])
  page_size = options[:page_size] || 100

  end_cursor = ""
  loop do
    query = <<-GRAPHQL
{
  viewer {
    login
    sponsorshipsAsMaintainer(includePrivate: true, first: #{page_size}, after: "#{end_cursor}") {
      totalCount
      pageInfo {
        endCursor
        hasNextPage
        startCursor
      }
      edges {
        node {
          id
          privacyLevel
          createdAt
          sponsor {
            email
            login
            name
          }
        }
      }
    }
  }
}
    GRAPHQL

    response = client.post '/graphql', { query: query }.to_json
    
    page = response[:data][:viewer][:sponsorshipsAsMaintainer]

    has_next = page[:pageInfo][:hasNextPage]
    end_cursor = page[:pageInfo][:endCursor]

    sponsors += page[:edges].map do |edge|
      sponsor = edge[:node]

      created_at = Date.parse(sponsor[:createdAt])
      now = Date.today
      months = (now.year*12 + now.month) - (created_at.year*12 + now.month) + 1
      sponsor[:months] = months

      sponsor
    end

    break unless has_next
  end

  sponsors 
end
