name: Execute fastlane

on:
  pull_request:
    branches:
      - master

jobs:
  build_dev:
    name: Execute fastlane
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Ruby Dependencies
        run: bundle install


      - name: fastlane
        run: |
          bundle exec fastlane update

