name: Execute fastlane

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build_dev:
    name: Execute fastlane
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Ruby Dependencies
        run: |
          sudo gem install bundler
          bundle install

      - name: fastlane
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN  }}:  
          MATCH_DEPLOY_KEY: ${{ secrets.MATCH_DEPLOY_KEY  }}
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
          MATCH_READONLY: true
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${MATCH_DEPLOY_KEY}"
          bundle exec fastlane update

