name: Execute fastlane

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build_dev:
    name: Execute fastlane
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.5'
          bundler-cache: true

      - name: fastlane
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          MATCH_DEPLOY_KEY: ${{ secrets.MATCH_DEPLOY_KEY }}
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
          MATCH_READONLY: true
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${MATCH_DEPLOY_KEY}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER }}"
          bundle exec fastlane update

